### ISSUE TITLE
[Suggestion] Audio components

### ISSUE THREAD

**Issue by tmutimer** [hyperdiv/hyperdiv#13]
Apologies if there's some other way that makes this unnecessary, but I can't think of a way to use audio in a hyperdiv app.

It would be awesome to be able to instantiate an `hd.audio` component and control playback using hyperdiv interactivity.

```python
whalesong = hd.audio("/path/to/whalesong.mp3")
if hd.button("Play whalesong").clicked:
    whalesong.play()
```

**Comment by mariusnita** [comment]
Thanks! There's no audio component currently but one can be added.

**Comment by mariusnita** [comment]
I added a basic audio component that will be in the next release: #26
