### ISSUE TITLE
Make "hyperdiv docs" available online

### ISSUE THREAD

**Issue by ziqbal** [hyperdiv/hyperdiv#2]
Maybe I have not checked thoroughly but it would be nice to have the "hyperdiv docs" available online somewhere, either as html or PDF.

Its a great feature to have the docs builtin but I'm running stuff in containers several layers deep and having to battle with seeing the docs and play testing within the same environment is not so easy.

**Comment by mariusnita** [comment]
I'll host it online soon, probably on https://docs.hyperdiv.io - stay tuned.

**Comment by fliepeltje** [comment]
I hacked together a quick temporary version until @mariusnita gets the official docs up :)

https://hyperdiv-docs-tmp.fly.dev/introduction/overview

**Comment by mariusnita** [comment]
Nice ;-) It looks like the Reference/Hyperdiv API links aren't working. 

I'll put the docs up soon.

**Comment by ziqbal** [comment]
@mariusnita Thanks for that. When I get some time I'll try to experiment more.
