### ISSUE TITLE
Ability to add a stylesheet to the index template

### ISSUE THREAD

**Issue by calexicoz** [hyperdiv/hyperdiv#21]
Howdy,

First of all, thanks for this great project!

It would be nice if there was a generic way to customize the `head` tag and add javascript/styles. At the moment, I work around things this way ↓. It works, but it's super hacky.

```python
def my_index_page():
    template_contents = index_page_template(title="Hyperdiv")
    template = Template(template_contents)
    return template.render(
        body="""
<script>
if (!document.querySelector('link[href="/assets/css/style.css"]')) {
    var linkElement = document.createElement("link");
    linkElement.rel = "stylesheet";
    linkElement.href = "/assets/css/style.css";
    document.head.appendChild(linkElement);
}
</script>
"""
    )

hd.run(main, index_page=my_index_page())
```

I use this to import custom fonts, and factor out various things. So any way to make this easier would be welcome.

Thanks!

**Comment by mariusnita** [comment]
Nice hack :) Do you mind sharing more about your use case beyond importing fonts?
