### ISSUE TITLE
integrating arbitrary third party javascript library as hyperdiv components

### ISSUE THREAD

**Issue by johnny-smitherson** [hyperdiv/hyperdiv#24]
By [editing the index page](https://github.com/hyperdiv/hyperdiv/issues/21) we can inject `<script>`s from `assets/` and run arbitrary javascript on the page. But there doesn't seem to be any way to interact with it in a way to enable further integrations.

Say, for example, we wanted to add some [D3.js visualizations](https://d3js.org/) or some [cytoscape graph interface](https://js.cytoscape.org/#core/graph-manipulation) or [the grid component you listed in the other issue](https://www.ag-grid.com/).

The ecosystem for web is much better for JS than it is for python (matplotlib wasn't really designed for web interactivity) - I think it makes sense to have a JS "escape hatch" for doing complex things, or some known recipe for interacting with the browser javascript engine.

Say, for the sake of discussion, I want to add a new component type [`D3JS_XKCD_Chart`](https://dfm.io/xkcd/) with some additional custom functionality strapped on top of the javascript (a checkbox to turn colors on and off).

Looking at the [Chart.js file](https://github.com/hyperdiv/hyperdiv/blob/main/frontend/src/components/chart.js) and the [chart.py file](https://github.com/hyperdiv/hyperdiv/blob/main/hyperdiv/components/charts/chart.py#L56) I can see the following parts of the component lifecycle:

1. JS: [register component frontend class in component mapping](https://github.com/hyperdiv/hyperdiv/blob/f7e44718f484a280cec2add916ea5ce201a914b6/frontend/src/components.js#L48-L49)
1. PY: some [`Component` subclass](https://github.com/hyperdiv/hyperdiv/blob/f7e44718f484a280cec2add916ea5ce201a914b6/hyperdiv/components/charts/chart.py#L7) is added to the page, gets rendered into json and sent over websocket
3. JS:  match registered class, create DOM element, [maybe edit it too depending on Component props](https://github.com/hyperdiv/hyperdiv/blob/f7e44718f484a280cec2add916ea5ce201a914b6/frontend/src/components/chart.js#L85-L92)
4. JS: instantiate [custom javascript stuff](https://github.com/hyperdiv/hyperdiv/blob/f7e44718f484a280cec2add916ea5ce201a914b6/frontend/src/components/chart.js#L94) on the DOM element created above
5. JS: register interaction callbacks that send websocket traffic [(example from checkbox, since  Charts have no interactivity)](https://github.com/hyperdiv/hyperdiv/blob/f7e44718f484a280cec2add916ea5ce201a914b6/frontend/src/components/checkbox.js#L5-L13)
6. PY: the prop sent over websocket is [automatically updated in the python object](https://github.com/hyperdiv/hyperdiv/blob/f7e44718f484a280cec2add916ea5ce201a914b6/hyperdiv/components/checkbox.py#L33) and the app re-runs with the new state

I think arbitrary component setup could be achieved by allowing additions to the [frontend component mapper](https://github.com/hyperdiv/hyperdiv/blob/main/frontend/src/components.js#L40) here - I'll try to hack a change in that global with a `<script>` tag and report further problems here

Questions:
- ~~how is the class matched? I see in JS the key is [checkbox](https://github.com/hyperdiv/hyperdiv/blob/f7e44718f484a280cec2add916ea5ce201a914b6/frontend/src/components.js#L49) but in python the `_tag` is [sl-checkbox](https://github.com/hyperdiv/hyperdiv/blob/f7e44718f484a280cec2add916ea5ce201a914b6/hyperdiv/components/checkbox.py#L25) - is it by python class name?~~ [by _tag](https://github.com/hyperdiv/hyperdiv/blob/f7e44718f484a280cec2add916ea5ce201a914b6/frontend/src/components.js#L80-L82)
- Any suggestions on using the [`registerPlugin` published function here?]( https://github.com/search?q=org%3Ahyperdiv+registerPlugin&type=code)

I also see some [undocumented code about plugins](https://github.com/search?q=org%3Ahyperdiv+plugin&type=code) - any samples you can share?

---

**Comment by johnny-smitherson** [comment]
I figured it out after trial and error, I can say the thing works great!


Here is a sample python file:

```py
import hyperdiv as hd

class SuperCustomDialog(hd.Plugin):
    x_prompt = hd.Prop(hd.String, "EMPTY PROMPT")
    x_status = hd.Prop(hd.String, 'status not initialized')
    x_disagreed_with = hd.Prop(hd.BoolEvent, False)
    x_agreed_with = hd.Prop(hd.BoolEvent, False)
    x_interacted_with = hd.Prop(hd.BoolEvent, False)

    # _assets = [('js-link', 'assets/super_custom_dialog.js')]  -- error 403 cannot find /plugins/SuperCustomDialog.js
    _assets = [('js-link', 'http://localhost:8888/assets/super_custom_dialog.js')]


def main():

    def make_super_dialog(title):
        with hd.scope(title):
            hd.text('instance: ' + title)

            with hd.box(padding=0.3, gap=0.3,border="1px solid blue"):
                custom_dialog = SuperCustomDialog(key='XXXSuperCustomDialog' + title, x_prompt=f'Do you agree with {title}?')
                if custom_dialog.x_interacted_with:
                    hd.text(f'(py {title}) interaction finished.')
                else:
                    hd.text(f'(py {title}) interaction pending.')

                if custom_dialog.x_agreed_with:
                    hd.text(f'(py {title}) You agreed.')
                elif custom_dialog.x_disagreed_with:
                    hd.text(f'(py {title}) You disagreed.')

                hd.text(f'(py {title}) status = {custom_dialog.x_status}')
            
            if hd.button(f'(py {title}) Edit Property').clicked:
                custom_dialog.x_status = f'(from py {title}) Clicked the button created from Python.'
                
    make_super_dialog('A')

    make_super_dialog('B')

```

Here is a sample js file (place at `assets/super_custom_dialog.js`):

```js
// Anon function required to avoid redefinition of `const hd = ` when we instantiating component twice.
(function() {

const hd = window.hyperdiv;

/// Plugin constructor has 3 arguments: key (the html element id), the shadow DOM root, and initial props.
/// **WARNING**: `initialProps` keys are mangled from snake_case into javaCase.
hd.registerPlugin('SuperCustomDialog', function(key, shadow_root, initial_props) {

    const jsStatus = document.createElement('div');
    shadow_root.appendChild(jsStatus);

    jsStatus.textContent = '(js) status = ' +  initial_props.xStatus;

    const jsMessages = document.createElement('div');
    shadow_root.appendChild(jsMessages);
    jsMessages.textContent = 'JS CONSOLE: ';
    jsMessages.setAttribute('style', 'white-space: pre;');

    const console_log = function(...args) {
        console.log(...args);
        jsMessages.textContent = (jsMessages.textContent || '') + '\n> ' + args.join(' ');
    };
    
    console_log('Init plugin component name = ', shadow_root.host.component.name);
    console_log('Init plugin component key = ', key);
    console_log('shadow_root', shadow_root);
    console_log('initial props: ', initial_props)

    console_log('creating button');
    const newButton = document.createElement('button');
    shadow_root.appendChild(newButton);
    newButton.textContent = '(js) Click me!';

    // Update python compoenent property - property name not mangled.
    hd.sendUpdate(key, 'x_status', '(from js) just loaded.')
    jsStatus.textContent = '(js) status = ' +   '(from js) just loaded.';

    newButton.addEventListener('click', () => {
        console_log('sending alert()');
        if (window.confirm(initial_props.xPrompt)) {
            console_log('You agreed.');
            hd.sendUpdate(key, 'x_agreed_with', true);
        } else {
            console_log('You agreed.');
            hd.sendUpdate(key, 'x_disagreed_with', true);
        }
        hd.sendUpdate(key, 'x_interacted_with', true);
      });
    

    // the constructor returns property update function.
    // **WARNING**: Prop key is mangled from snake_case into javaCase.
    return function(prop_key, prop_value) {
        console_log('updated property key', prop_key);
        console_log('updated property value', prop_value);

        if (prop_key == 'xStatus') {
            jsStatus.textContent = '(js) status = ' +  prop_value;
            console_log('updating status = ', prop_value)
        }
    };
});

})();

```

The above show bi-directional communication using `hd.sendUpdate` from the browser and normal use from python.

Take-aways:
- python class definition `_assets` does not work with paths (tries to load the js file from the wrong place)
- javascript `init_props` and update `prop_value` get mangled from `snake_case` to `javaCase`, but sending messages back doesn't have the same mangling function - so your JS code needs to mix prop case type

**Comment by mariusnita** [comment]
Nice find ;-)

Yes I want to add support for third-party components and the undocumented Plugin is the first stab at it. It's undocumented because it's unpolished/unfinished and more importantly, I'm not sure if this is the most robust approach to supporting extensions. It's nice because it injects JS directly into the page and the plugin is a Web Component whose CSS is scoped. But in this approach there's no way to sandbox the JS, so plugins can step on each other. Also, in this approach it's not straightforward, to my knowledge so far, to integrate React/Svelte/etc. components.

I think the most robust way to do plugins is probably iframes, where you can build the custom component as a mini standalone app that runs sandboxed and exchanges messages with the top-level Hyperdiv page.

**Comment by johnny-smitherson** [comment]
>  plugins can step on each other

How? Each plugin instance gets its own shadow dom node with `id = ` key that it was instanced with - sounds pretty easy to me to keep them separate.
You mean if they rely on globals/`window.X`? Sounds like a feature and not a bug.

>  iframes

That doesn't sound very friendly with:
-  performance problems if you want to have hundreds/thousands of instances of custom plugin elements (think, a custom button or tooltip or table cell)
- weird browser controls (right click inside iframe has back/forward buttons specific to the iframe, for example)
- accesibility problems (each iframe in a screen reader is dictated as a separate page)
- composability: iframe inside iframe? inside another iframe...

Anyway, I got what I wanted - feel free to copy/paste the examples above into a possible doc page if you want to keep this approach

**Comment by johnny-smitherson** [comment]
My suggestions for this implementation of Plugin would be:

- don't mangle the prop `x_status` into `xStatus`
- call the js prop update callback after `x.sendUpdate` is called, to make it easy to communicate between two known plugins with known keys
- finalize/remove [the plugin asset loader complication](https://github.com/hyperdiv/hyperdiv/blob/f7e44718f484a280cec2add916ea5ce201a914b6/hyperdiv/plugin.py#L28-L35) - maybe make that link `/assets/plugins/$CLASSNAME.js` or some other convention?

**Comment by mariusnita** [comment]
> Each plugin instance gets its own shadow dom

I mean all the JS gets included at the top level with `<script>` tags. The CSS is sandboxed but there's no way to sandbox JS with Web Components.

**Comment by johnny-smitherson** [comment]
You mean these? 

<img width="393" alt="Ca23pture" src="https://github.com/hyperdiv/hyperdiv/assets/127537716/f45a1ae3-4b45-455d-a6c8-ec274127f22b">

But that's what I would've done anyway by hacking the template. That's also what would happen if they got `npm installed` and bundled up together by a minifier, right?

They won't even duplicate after spawning 2 of the same Plugin, which is great.

I don't see component isolation as a thing that's mainstream yet - [some proposal here](https://github.com/WICG/webcomponents/issues/1002).

My JS knowledge is pretty much done after this point - I don't know how isolation problems happen. Some [forum people are talking about huge apps with many versions of the same lodash.js](https://stackoverflow.com/questions/50498183/isolate-webcomponent-js-libraries) - is that case what you're worried about?

**Comment by mariusnita** [comment]
> `SuperCounter(key='super_counter')`

Btw I don't think you have to pass `key`. It should be auto generated.

**Comment by mariusnita** [comment]
Wrt isolation - yeah I agree JS isolation might not be the main thing to be worried about.

I am interested though in easily supporting plugin development using the usual npm workflow. I need to explore that more.

**Comment by johnny-smitherson** [comment]
I think it's worth it to share a vision and scope for this project.

Personally, I see it as replacement for Gradio, Plotly Dash and others - the main advantage being there is no mandatory CDN script that is required (for telemetry probably) into every single HTML page generated by those libraries. Those services don't work properly in an offline setting, for example, this system does.

That being said, I would use this for data dashboards, with very limited extra javascript code (for example graph explorers like in the first comment).

One thing I was wondering about, where the npm build happens, where the bundle.js comes from. By downloading the wheel I see it's generated at package upload time - great! Not having to interact with `npm` is a great feature for me - especially considering source code from 1-2 years ago never builds anymore in that ecosystem.

**Comment by johnny-smitherson** [comment]
So maybe a possible solution would be to put the plugins in PyPI (with more pre-built bundles) instead of using NPM, that way most of users can avoid ever installing NPM ever again (unless they want to make a plugin)

**Comment by mariusnita** [comment]
Yeah I see Hyperdiv as a way to easily build apps with zero JS, without depending on the JS ecosystem, for 95% of developers. But I think in the long run a healthy third-party plugin ecosystem will be critical for its success. So the other 5% are plugin developers who do depend on Javascript. They create Hyperdiv plugin packages that contain custom JS/CSS bundles and deploy them on PyPI. Then the 95% `pip install` those plugins and use them in their apps, much like they'd use any Hyperdiv component.

You can build and publish such a package now using the Plugin interface, but I do think supporting npm workflow/guidelines for the 5% will be important.

**Comment by johnny-smitherson** [comment]
Ah, you mean npm only for the plugin devs - that's great!

Let me know if you write up some guides, I'll contribute some `D3.js/cytoscape.js` or what I happen to be using until then

**Comment by mariusnita** [comment]
@johnny-smitherson Check out this thread https://github.com/hyperdiv/hyperdiv/issues/36#issuecomment-1984554386

Providing the absolute on-disk path to `js-link` and `css-link` should load the plugin assets correctly.

**Comment by johnny-smitherson** [comment]
yes it works with this

```

    
    _assets = [
        ('js-link', (os.path.join(ASSETS_FOLDER_FULL_PATH, "cytoscape.all_min.js"))),
        ('js-link', (os.path.join(ASSETS_FOLDER_FULL_PATH, "cytoscape_wrapper.js"))),
        ('css-link', (os.path.join(ASSETS_FOLDER_FULL_PATH, "cytoscape_wrapper.css"))),
    ]
```

thanks!

**Comment by mariusnita** [comment]
Btw I'm going to slightly rewrite the Plugin interface and officially document it, in the next release. It'll break current plugins but will be an easy fix. In my current draft a plugin looks like this:

```py
class my_plugin(hd.Plugin):
    # The assets root:
    assets_root = os.path.join(os.path.dirname(__file__), "assets")
    # These will be relative to the assets root:
    assets = [
        hd.Plugin.js_link("foo.js"),
        hd.Plugin.js_link("build/foo/bar.js"),
        hd.Plugin.css_link("foo.css"),
    ]
```

The main difference is you define an `assets_root` and then the assets links are relative to that root. And the plugin JS can load any other assets from that root, not just the ones listed in `assets`.

Let me know if you have feedback on this.

**Comment by johnny-smitherson** [comment]
feedback? sure maybe

```
class my_plugin(hd.Plugin):
    # The assets root:
    assets_root = os.path.join(os.path.dirname(__file__), "assets")
    assets = [
        "foo.js",
        "build/foo/bar.js",
        "foo.css",
    ]
```

and you auto-wrap them in the funny class functions depending on extension.

For unknown extensions user must wrap them explicitly with `hd.Plugin.js_link` and friends

**Comment by johnny-smitherson** [comment]
if you feel extra magic, you can have the `assets_root` be optional , with the default being what you just wrote for it (the folder right next to where you define the plugin). You can use importlib to find out the file, and a metaclass to only do it once

```
import importlib
import os

class DefaultAssetRootMetaclass(type):
    def __new__(cls, name, bases, attrs, **kwargs):
        module_file = importlib.import_module(attrs['__module__']).__file__
        default_assets = os.path.join(os.path.dirname(module_file), 'assets')
        attrs.setdefault('assets_root', default_assets)
        return super().__new__(cls, name, bases, attrs, **kwargs)
    

class PluginBase(metaclass=DefaultAssetRootMetaclass):
    pass
```

**Comment by johnny-smitherson** [comment]
Then again, `asset_root` and `asset_dir` and all these will intersect with the property names you want to put directly in the plugin definition:


```
class CytoscapeJsWrapper(hd.Plugin):
    elements = hd.Prop(hd.String, json.dumps([]))
```


Maybe my plugin will also have an `asset_root` and the conflict will burn my brain - django has the `Meta` class for this. You can do it too with

```
class my_plugin(hd.Plugin):
    class Assets:
        assets_root = X
        scripts = 'src/**/*.js'
        stylesheets = 'src/**/*.css'

**Comment by mariusnita** [comment]
> Maybe my plugin will also have an asset_root

This is why in the current undocumented Plugin `_assets` is prefixed by `_`. Maybe it should stay that way. Using an `Assets` class is also interesting.

**Comment by johnny-smitherson** [comment]
yes but then i've got `assets` which is my assets, `_assets` which is your assets, but at a glance, without thinking about it, it looks like `_assets` is my assets, since it's got the underscore for private dirty things to do in the plugin - so you end up walling against this by putting comments and whitespace around like so

```
class CytoscapeJsWrapper(hd.Plugin):
    _assets = [
        ('js-link', (os.path.join(ASSETS_FOLDER_FULL_PATH, "lib", "cytoscape.all_min.js"))),
        ('js-link', (os.path.join(ASSETS_FOLDER_FULL_PATH, "cytoscape_wrapper.js"))),
        ('css-link', (os.path.join(ASSETS_FOLDER_FULL_PATH, "cytoscape_wrapper.css"))),
    ]
    ###########################

    celements = hd.Prop(hd.String, json.dumps([]))
    cstyle = hd.Prop(hd.String, json.dumps([]))
    cmenu = hd.Prop(hd.String, json.dumps([]))
    clayout = hd.Prop(hd.String, json.dumps({}))
    assets = hd.Prop(hd.String, '')
    menu_event = hd.Prop(hd.StringEvent, '')
    selected_items = hd.Prop(hd.String, '')#
```

I feel like this "settings" class is the inevitable direction that was taken the moment class fields are used in this declarative way, because it also gives better visual structure to the noise above

**Comment by johnny-smitherson** [comment]
Another pattern I see out of said conflict paranoia is encapsulating the plugin class before further use, since my cytoscape-related "styles" is going to clash with some hd component ancestor "styles", and so on - so you end up with stuff like this

```


class Cytoscape():
    def __init__(self, elements, style, menu, layout):
        self._elements = elements
        self._style = style
        self._menu = menu
        self._layout = layout
        self.wrapper = CytoscapeJsWrapper(
            celements=json.dumps(self._elements),
            cstyle=json.dumps(self._style),
            cmenu=json.dumps(self._menu),
            clayout=json.dumps(self._layout),
            assets='',
        )
    
    @property
    def elements(self):
        return self._elements
    
    @elements.setter
    def elements(self, value):
        self._elements = value
        self.wrapper.celements = json.dumps(self._elements)

```

I think it would be cool to have a standard way to hook into the props to translate/validate/process them before they go into the websocket, and for messages after the come out of the websocket. I could then tell the prop definition inside the plugin, hey, use `json.dumps` going in and `json.loads` going out
