### ISSUE TITLE
text input autocomplete provider

### ISSUE THREAD

**Issue by sirfz** [hyperdiv/hyperdiv#29]
Just came across hyperdiv as I needed to build a simple prototype app and I'm really liking it compared to all other frameworks I tried out (despite the limited scope I used them for).

It seems that the text autocomplete feature doesn't exist in any of the frameworks I tried (and I tried several since yesterday much to my frustration). I'm not a web developer by any means so I might be missing something obvious.

Is it possible to add some kind of callback to a text_input component through which we can display autocomplete options to the user? (something similar to Google search box for reference).

**Comment by johnny-smitherson** [comment]
You have to build the UI yourself like this:

```py
def main():
    def make_suggestions(query):
        return [query[:int(len(query)/2)], query[int(len(query)/2):]]
    
    with hd.form() as form:
        textarea =     form.textarea('Search:')

    hd.markdown('Suggestions:')
    s_list = make_suggestions(textarea.value)
    for i, suggestion in enumerate(s_list):
        with hd.scope(i):
            suggestion_box = hd.button(suggestion)
            if suggestion_box.clicked:
                textarea.value = s_list[i]
```

You would then play with the styling to make the buttons not look like buttons, and add extra state/events to render the rest of the page.

**Comment by sirfz** [comment]
Thank you for the suggestion! I had to modify the approach using `task.rerun` to generate suggestions and update the state then render the suggestions when they exist in the state. That worked pretty well for me.

It would be a great feature if the suggestions could be rendered within the text box's autocomplete drop down.

**Comment by mariusnita** [comment]
> any idea how to customize the debounce interval (or if debounce is even implemented?)

Yeah it's debounced and currently you can't customize the debounce interval. It has been on my list to make these configurable.

> is there a way to submit the form from python, for example form.submit() in the above click handler?

No but it should be straightforward to add a submit() method to form.

**Comment by mariusnita** [comment]
> It would be a great feature if the suggestions could be rendered within the text box's autocomplete drop down.

There's a missing `popup` component in Hyperdiv that I plan to add. With this component, you can attach a "dropdown" to the text input and render the suggestions in there.

**Comment by mariusnita** [comment]
Hi, there's a new `popup` component in the latest release that will get you closer to what you want. See an example here: https://docs.hyperdiv.io/reference/components/popup
