### ISSUE TITLE
Increased control of ticks and scale on charts

### ISSUE THREAD

**Issue by tmutimer** [hyperdiv/hyperdiv#34]
Hi,
If you like the below idea I would happily work on a PR to add it.

I would like to be able to control the min max (suggestedMin and suggestedMax) and whether the y tick labels are shown. I can see that chart.js provides this functionality.

My reason is that if you have a data that's going to evolve as you interact with the app, you may want a predefined scale, and if you are doing something with percentages (like I was currently trying to do with `radar_chart`), then the absolute values don't really matter because you can see the progress visually.

I imagine it would work something along the lines:

```
hd.radar_chart(
    (1,2,3,4),
    axis=("First, 'Second', 'Third', 'Fourth'),
    y_min=0,
    y_max=100,
    hide_y_tick_labels=True
)
```

And similarly for the other types of chart.

**Comment by mariusnita** [comment]
Hi, this sounds cool and I've had similar thoughts about pinning the y-range for evolving data. Maybe the flag to show the tick labels should exist for both axes. You should do a PR.

**Comment by tmutimer** [comment]
PR in: #35
