### ISSUE TITLE
incorrect url for javascript asset produced for plugins that define a file-based js-link

### ISSUE THREAD

**Issue by tkriplean** [hyperdiv/hyperdiv#36]
Consider a plugin with `_assets = [('js-link', f"./assets/myplugin.js")]`

Hyperdiv will produce a <script src="/plugins/myplugin/myplugin.js"></script> in the header that returns a 403 because Tornado recognizes the file is not in the root static directory (and even if it was, the file doesn't exist there).

I'm pretty sure the error is at https://github.com/hyperdiv/hyperdiv/blob/9fffc6d45511f9a4f58d895fd294f704d8264956/hyperdiv/plugin.py#L32-L35
That code replaces the correct link to the javascript (e.g. /assets/myplugin.js) with an incorrect one (e.g. /plugins/myplugin/myplugin.js).

Note that I would actually love if I could put myplugin.js in a directory myplugin in the plugins directory, so the js and py plugin files could be together. Which I imagine would entail allowing javascript files in plugin directories to be served as static assets. 

(I know plugin.py is undocumented and unsettled, so please feel free to ignore if you're not spending time in there)

**Comment by mariusnita** [comment]
Thanks! Aware of this bug. I plan on fixing and documenting Plugin.

Just curious, how do you plan on using Plugin?

**Comment by tkriplean** [comment]
I have two different plugins that are working:
1) OAuth2 login flow (working with Google)
2) YouTube embed component

I would be happy to share code / discuss / help pilot, if that would be useful.

**Comment by mariusnita** [comment]
That's awesome!

**Comment by mariusnita** [comment]
Can you share a minimal plugin setup that breaks? Plugin stuff is unfinished and got deprioritized for the release but I plan to fix it.

My intent for Plugin was that a plugin writer could make a bundle like:

```
my_plugin/
  my_plugin.py
  assets/
    my-plugin.js
    my-plugin.css
```

The plugin in `my_plugin.py` would look like:

```py
class my_plugin(hd.Plugin):
  _assets = [
    hd.Plugin.js(os.path.join(os.path.dirname(__file__), 'assets', 'my-plugin.js')),
    hd.Plugin.css(os.path.join(os.path.dirname(__file__), 'assets', 'my-plugin.js'))
  ]
```

The plugin could be stored in some arbitrary directory on disk. (Like hypothetically if you pip installed a plugin, its assets would be deep in the virtualenv directory.) When a Hyperdiv app imports and uses that module, it would serve its files from `/plugin/my_plugin/my-plugin.js` and `/plugin/my_plugin/my-plugin.css`. Those are "virtual paths" that serve the actual files on disk under the hood.

**Comment by tkriplean** [comment]
Sure, here is a minimal setup that breaks: https://github.com/tkriplean/hello_world_plugin

**Comment by mariusnita** [comment]
Thanks! Try passing the absolute path of the asset file on disk, in `js-link`.

```py
("js-link", os.path.join(os.path.dirname(__file__), "..", "assets", "helloworld.js")
```

The `".."` is because in your setup the plugin assets dir is stored one directory level higher than `helloworld.py`.

The plugin bundle should probably be structured like this:
```
helloworld/
  helloworld.py # The HelloWorld definition
  assets/ # JS/CSS assets that HelloWorld depends on
    helloworld.js
    helloworld.css
```

And then the `js-link` would not have the `".."` in it:

```py
("js-link", os.path.join(os.path.dirname(__file__), "assets", "helloworld.js")
```

**Comment by tkriplean** [comment]
Thanks! That seems to do the trick. Glad to also be able to restructure the plugin too. As far as I'm concerned, this closes the issue.

**Comment by mariusnita** [comment]
Sweet! Thanks! I plan on fleshing out and documenting Plugin soon.
