### ISSUE TITLE
Expand Support for Format String Syntax in Router

### ISSUE THREAD

**Issue by weketoj** [hyperdiv/hyperdiv#37]
Since route parameters already use python's `parse` under the hood, I wanted to try using a format spec to parse a number (as an example) during the matching of the route, instead of handling it in the route's logic. 

`router.run()` isn't a fan of this, though, since it creates a new scope for the route's bound function, with `hd.scope(route + ":" + "#".join(args))`, and `parse` returns an integer instead of a string, causing the join to fail. 

Could fix by mapping `str` over the args before joining them for the new scope (`hd.scope(route + ":" + "#".join(str(arg) for arg in args))`)? Reproducible example of the problem below.

```python
import hyperdiv as hd

router = hd.router()

@router.route("/{num:d}")
def number(num):
    hd.text("Number,", num)

def main():
    router.run()

hd.run(main)
```

Navigate to /123 to see the `hd.scope` call fail

**Comment by mariusnita** [comment]
Good idea! Seem like an easy fix.

**Comment by weketoj** [comment]
Thanks! Really cool tool you've made, I've had a lot of fun with it already.
