### ISSUE TITLE
"Helper" Components could return their top-level Component

### ISSUE THREAD

**Issue by weketoj** [hyperdiv/hyperdiv#39]
Was using `icon_link`s, and was looking for a way to read the value of its "clicked" prop. I noticed that `icon_link` assembles a `link` component, but then doesn't return it. In more complicated components it may not be obvious what to return, but in the case of something like `icon_link`, it should probably return the `link` so that it can be used by the caller.

**Comment by mariusnita** [comment]
I added this commit https://github.com/hyperdiv/hyperdiv/commit/245dd3cf606fcb433d49e215477c3927f97c7626

In the next version you'll be able to do:
```py
link = hd.icon_link(...)
if link.clicked:
  ...
```
