### ISSUE TITLE
when clicking an hd.link nested in an hd.tab, the link is followed but the active tab is not updated

### ISSUE THREAD

**Issue by tkriplean** [hyperdiv/hyperdiv#42]
The active tab doesn't change when a tab is clicked if there is a link nested in it. This isn't terribly surprising, but it would be nice to handle this pattern as I imagine it will be a common use case for tabs. 

Sample app:

```
import hyperdiv as hd

router = hd.router()


@router.route("/")
def home():
    hd.text("home")


@router.route("/hello")
def hello():
    hd.text("hello")


@router.route("/hello/world")
def helloworld():
    hd.text("helloworld")


def main():
    with hd.box(align="center"):
        with hd.tab_group() as tabs:
            with hd.tab():
                hd.link(
                    "home",
                    href="/",
                )

            with hd.tab():
                hd.link("hello", href="/hello")

            with hd.tab():
                hd.link("helloworld", href="/hello/world")

    router.run()


hd.run(main)
```

**Comment by tkriplean** [comment]
The addition of padding to the tab wrapper div also makes this pattern difficult to use, as a click on the wrapper (but not link) will cause the tab to change but the link to not be followed. 
![image](https://github.com/hyperdiv/hyperdiv/assets/707039/627cdefd-f85d-429c-8b7f-5f1c04109c99)

**Comment by tkriplean** [comment]
I'd love it if hd.tab could simply accept an href prop and handle it gracefully, but I realize that may not be a graceful separation of function...

**Comment by mariusnita** [comment]
Hmm I will look into this but I think this is akin to nesting a link within a button which is an HTML anti-pattern.

**Comment by tkriplean** [comment]
Well that's interesting! As far as I know, tabs aren't canonically buttons. And even the Hyperdiv implementation doesn't produce buttons. Having tabs that change urls is a common pattern (e.g. navigation menus). The icon_link and topbar_links in app template are essentially a tab group. I'd use a menu component but the styling isn't as compelling as the tag group styling. 

Maybe you're hoping to conceptually distinguish navigation menus from tab groups?

**Comment by tkriplean** [comment]
Was mulling this a little bit more. 

The original metaphor of a tab is a bunch of folders with labeled tabs on them. Tab UIs, at least traditionally, actually show the tab combined with the folder. Like: 
![image](https://github.com/hyperdiv/hyperdiv/assets/707039/1294b809-915e-479c-ae1c-fb886160436b)

However, trends have moved away from that integrated folder view to a sort of implied container, where you're just switching between views with some light indicator of change. This UI trend has essentially led to very little visual distinction between tabs and navigation menus. To add even more confusion to the mix, "tabbed navigation" is a core UI pattern on mobile interfaces. That's what hd.tab_group produces by default:

![image](https://github.com/hyperdiv/hyperdiv/assets/707039/58367cf1-9ec4-4ffc-814b-5ba2f75cc766)


Some UI purists distinguish tabs from navigation in terms of pages: If you're switching between "pages", use a nav menu. If you're switching between views of conceptually related items, use tabs. However, to me, this is a bit weird because the very idea of different "pages" is outmoded. Even if tabs are for switching between views of conceptually related items, why shouldn't each view get its own url? Urls can bookmark state that we want the UI to recreate, so we can return to it later or share with others. 

So, hd.tab_group / hd.tab are not designed with the traditional strong visual tab metaphor in mind. If they were, I would expect the tab component to also incorporate a "container" in which the different views will be rendered. 

Instead, tab_group renders a styled group of divs with text, where one can be active at a time. And thats it. This makes it very flexible for use within a navigation context or a traditional tab context. But its design isn't making a strong commitment one way or another, and I don't see why its an anti-pattern to include a link in the divs. 

If you're hoping to strongly distinguish navigation menus from tab groups, I'd consider:
1) create a tab component that is a box with slots for a tab_group and a container, and defaults to having the active tab with the same background color as the background color of the container in which views are rendered. This is actually a bit tricky to implement especially when the tabs have borders on it. 
2) offer the current tab_group / tab styling as a variant for the navigation menu 

Even then, I don't see why you wouldn't want to have a way for the url to change depending on which tab is selected.

**Comment by mariusnita** [comment]
One aspect to keep in mind is low vision users and screen readers. There, concepts like nav, links, and tabs convey different meanings and expectations. 

I think your question really is analogous to "why shouldn't I put a link within a button?"

I think the answers there ultimately start to touch on semantic expectations of the HTML tags you use.

Even if you fix the technical conflicts with nesting a link within a button, screen readers will see a button and not expect it to be navigational; and won't necessarily see that there's a link in there unless the user descends into the button contents to discover the link. You can further fix that with accessibility labeling and improved keyboard navigation.

Or you can just style a link to look like a button.

**Comment by tkriplean** [comment]
Hey Marius, I'm having a hard time understanding how what you're writing relates to the issue I'm reporting. 

To ground it a bit further, here's the tab interface I ended up creating (not using hd.tab though because of the issue I reported):

https://github.com/hyperdiv/hyperdiv/assets/707039/09bb4f53-0369-43ef-95fb-4e7d3aa5d760

The markup, for the equivalent of hd.tab_group, is:

![image](https://github.com/hyperdiv/hyperdiv/assets/707039/0c3d68dd-50a9-43fd-adec-868b081237db)

It uses a nav tag to house the links, visualized as a tab (ideally that div between the nav and links wouldn't be there, but I couldn't figure out how to get the nav to be a flexbox). There are no buttons. This is semantically correct use of HTML tags that is completely accessible by any accessibility standard out there.

The only way I can make sense of what you're saying is to imagine that you think tabs are semantically always buttons. Is that so? Or was there a misunderstanding somewhere along the way?

**Comment by mariusnita** [comment]
Sorry for being obtuse with my links in buttons analogy. I totally failed to convey meaning there.

This is my summary of what I believe you're asking at the beginning of this thread: "I want to implement tabbed nav. Tabs are a common metaphor for navigation. Hyperdiv has a tabs component. Hyperdiv's tabs don't work for navigation. They probably should."

This argument is intuitive, and I can reuse it for HTML buttons (this is my failed 'buttons analogy'): "I want to implement nav that looks like buttons. Buttons are a common metaphor for navigation. HTML has buttons. HTML's buttons don't work for navigation. They probably should."

HTML's buttons don't work for well for navigation, for reasons ~identical to why Hyperdiv's tabs (`<sl-tab>`) don't work for navigation. These components are ultimately not intended for navigation, and you have to do a lot of work to coax them to work well for navigation, especially when you take screen readers into account.

OR, do what you did, which is the foolproof way to implement compliant navigation. Use `<nav>` and `<a>`, and style it to whatever visual metaphor you want for your sighted users: tabs, buttons, menus, etc.

That said, the docs should be more clear about nav, and maybe a "tabbed nav" component can be useful to add to Hyperdiv.

I'm closing this issue, because I don't plan to make `hd.tab_group` work for navigation. But we can continue the convo.

**Comment by mariusnita** [comment]
Btw resoundio.com is looking great!

**Comment by mariusnita** [comment]
I think it comes down to wanting a visual metaphor for a use case, seeing a component that matches the visual metaphor, but that component doesn't semantically match the use case.

Also see this related warning on Shoelace's menu component: https://shoelace.style/components/menu

> Menus are intended for system menus (dropdown menus, select menus, context menus, etc.). They should not be mistaken for navigation menus which serve a different purpose and have a different semantic meaning. If you’re building navigation, use `<nav>` and `<a>` elements instead.

Menus are another common visual metaphor for navigation.

**Comment by tkriplean** [comment]
I was looking at Shoelace's perspective last night, too. 

I think Shoelace has made a poor decision regarding tabs (and probably carousels too). Whereas menus are not always about navigation (e.g. when they're used to select a value), tabs are *always* navigation. They switch between views. That is exactly what internal links do. The difference is whether the url indexes the view change or not. That's why the interface to the tab component looks so similar to a router. Instead of checking the url for which view to render, you check which tab is active. To me, that isn't a semantic difference, it is a tiny mechanistic difference. 

Even if it was a semantic difference, like you say, a tab is a visual metaphor. If you're going to provide a component to implement a visual metaphor, why not support, with the correct semantic markup, the common patterns in which those visual metaphors are put to use? Why shouldn't I be able to specify that I want a tab component whose view changes are reflected in the URL, and expect that I'll get tab component that is wrapped in a nav with links? I know you said that maybe later there could be a tab nav component, which is great, but Shoelace doesn't provide one.

(I'm making a strong statement about tabs always being about navigation -- but, err, I'm open to counter examples, I could be wrong).

**Comment by tkriplean** [comment]
The shoelace slot for tabs in the tab group is even called nav lol

![image](https://github.com/hyperdiv/hyperdiv/assets/707039/d18a5507-ab9d-4a64-84f7-ac64002a47ff)

**Comment by tkriplean** [comment]
Okay, why is this question about tabs so captivating? Oh, because it is helping me procrastinate from doing taxes... 

Anyway, one difference between tabs and links that is worth mentioning is that the scope of the view change in a tab is confined to the tab container. However, a navigation menu has as its associated "container" the entire window -- a link to a different page could change everything, including not having the navigation menu. So a tab can provide more specific instruction to screen readers about what to focus on. Any good implementation of tabs, including with nav/links, will scope changes to only occur in the tab container. This can be achieved with aria markup even for navs and links (which I didn't do yet, and which is another argument for a component that does it right out of the box!)

**Comment by mariusnita** [comment]
Btw Hyperdiv has an incomplete implementation of Shoelace's tabs by not using tab panels. You noticed this idiosyncrasy earlier. It probably should bring in tab panels and conform to the interface exposed by Shoelace.

That said, this is what tabs are semantically: https://www.w3.org/WAI/ARIA/apg/patterns/tabs/

I think Shoelace conforms pretty tightly to this spec.

**Comment by tkriplean** [comment]
Yes, it narrowly conforms to it. It provides one particular limited implementation. And monopolizes the visual metaphor. Other valid and conforming implementations of the semantics are unsupported.

**Comment by mariusnita** [comment]
And navigation: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/navigation_role

I'm far from an expert on accessibility but issues become evident when you consider what a screen reader sees and what a low-vision user expects when they encounter the various elements on your page. I think when they encounter "tabs" they don't expect a navigation menu. And when they encounter a navigation menu they don't expect tabs to be nested in there. A navigational structure like:

```
nav
  tab group
    tab
      link
    tab
      link
```

would likely be confusing to read/discover and cumbersome to step thru with the keyboard. When the user steps into a tab, they won't know there's a link hidden in the tab unless they "descend" into the tab to find the link.

You could make a semantic tab group look like a navigation menu on a screen reader, but you'd have to modify it significantly, to where it no longer looks like tabs. The easiest way to achieve that is to forget about tabs, semantically, and just build a navigation menu with links.

You could possibly make a framework that provides a unified "tabs" API and look & feel, but "compiles" to different semantic structures.

Like, this makes tabs:
```py
tab_group("One", "Two", "Three")
```
And this looks identical but compiles to a nav menu:
```py
tab_group("One", "Two", "Three").as_nav({
  "One": "/one",
  "Two": "/two",
  "Three": "/three"
})
```

**Comment by tkriplean** [comment]
That's what aria is for. You add aria roles to say, hey, this is implementing tabs. Here are the tabs. Here is the tab container. Its like a contract. 

It would be very nice to have framework support for that. Otherwise devs will get frustrated and implement their own (like I did), and accessibility tags are often not added (e.g. I haven't yet).

**Comment by mariusnita** [comment]
Maybe a better way to look at Shoelace is that it primarily offers *component semantics* that also happen to have a built-in default look & feel. Its tab group provides a semantic implementation of the tabs ARIA spec.

It doesn't monopolize the look & feel, because you can implement the tabs visual metaphor any number of ways. And on screen readers those things will not look like tabs, since screen readers don't care about visual metaphors.

**Comment by mariusnita** [comment]
> Your points don't really bear upon low vision users.

Yeah apologies for messing up terminology. I do mean users of screen readers.

**Comment by tkriplean** [comment]
All I know is that for me, it is very limiting to provide a navigation component without an ability to reflect back to the url. Hi five I guess for narrowly covering the semantic space, but utility wise, perhaps not as much of a win as you might think. 

I just logged into my inaturalist account (as I continue procrastinating on doing taxes), and I see a TWO tab components that modify url:

![image](https://github.com/hyperdiv/hyperdiv/assets/707039/3b6be016-16f1-430a-ac07-51e6f7371c9e)

**Comment by tkriplean** [comment]
Maybe another way to look at this is that Shoelace is very precise, but its recall, at least for these navigation components, is quite low.

**Comment by mariusnita** [comment]
> Otherwise devs will get frustrated and implement their own (like I did), and accessibility tags are often not added (e.g. I haven't yet).

You probably don't need to add any accessibly tags if you're implementing a nav menu with `<nav>` and `<a>`. Those are automatically compliant and discoverable as navigation landmarks.

> It would be very nice to have framework support to produce tabs that get marked up with aria correctly

I concur with this sentiment, I just think it's hard to do generically. But I think it's possible to provide a semantic navigation menu that supports N visual metaphors: as tabs, as a menu, as buttons, etc.

**Comment by tkriplean** [comment]
> You probably don't need to add any accessibly tags if you're implementing a nav menu with <nav> and <a>. Those are automatically compliant and discoverable as navigation landmarks.

The tags would actually help. 

One difference between tabs and links that is worth mentioning is that the scope of the view change in a tab is confined to the tab container. However, a navigation menu has as its associated "container" the entire window -- a link to a different page could change everything, including not having the navigation menu. 

So a tab can provide more specific instruction to screen readers about what to focus on. Any good implementation of tabs, including with nav/links, will scope changes to only occur in the tab container.

So aria that designates tab behavior and labels the tab container allows the screenreader to assume that only the content in the container has changed after a tab is clicked.

**Comment by mariusnita** [comment]
As far as the iNaturalist thing, GitHub does the same. A tabs visual metaphor:

<img width="754" alt="image" src="https://github.com/hyperdiv/hyperdiv/assets/5980501/3c31fbee-e029-4af0-801b-2b94415277fd">

But if you inspect it it's a navigation menu built with `<nav>` and `<a>`, it's not ARIA tabs.

I think the conclusion here is that Hyperdiv should/could provide a navigation menu that follows the tabs visual metaphor. And update the docs to dissuade users from using `tab_group` for navigation, and point them to the nav menu that looks like tabs.

**Comment by tkriplean** [comment]
Github would be more accessible if they implemented it as a ARIA tabs.

Screenreaders have a built in a lot of hard won heuristics though and might recognize these common mistakes.

**Comment by tkriplean** [comment]
I spent about a month in a screenreader trying to make Considerit as accessible as possible, which is where this is coming from. I'm by no means an expert, but have had some concrete experience.

**Comment by mariusnita** [comment]
Thanks this is useful. I want to learn if `<sl-tab-group>` can be properly made navigational in a way that is obvious to blind users that switching tabs navigates to different URLs, and if this is an expected pattern.

Just curious, is the iNaturalist tab group ARIA tabs, or just a navigation menu like GitHub's?

**Comment by tkriplean** [comment]
> Just curious, is the iNaturalist tab group ARIA tabs, or just a navigation menu like GitHub's?

Neither. Another example of poor accessibility.

![image](https://github.com/hyperdiv/hyperdiv/assets/707039/a4d3e18b-4d63-4178-87ae-626cdf7de5f6)


Note that if you look in the iNat screenshot, there is ALSO a navigation tab element that is more like the github example. That one is marked up as:

![image](https://github.com/hyperdiv/hyperdiv/assets/707039/ab1418b1-8d7f-4262-8415-d67722d2add2)


Fixing these things is something frameworks can really help with!

**Comment by tkriplean** [comment]
FWIW, 

```
nav
  tab group
    tab
      link
    tab
      link
```

I think the tab group could render as a nav, and the tab render as a link.

**Comment by mariusnita** [comment]
> I think the tab group could render as a nav, and the tab render as a link.
 
Would your blind users know that this is a tab group, or you just advertise it as a nav menu with links?

Doing some research and it def seems possible to make an ARIA tab group that is also a crawler-compliant navigation menu. But this also seems like a niche case, not common. 

My core questions are (a) is tab group within nav expected? And (b) if it's expected, how is it typically structured and aria-labeled?

If you know of a resource on this, I'd appreciate a link.

**Comment by tkriplean** [comment]
Thanks, I'll get back to you on this. Want to take my time with a good answer.
