### ISSUE TITLE
vertical hd.divider gets height of 0

### ISSUE THREAD

**Issue by tkriplean** [hyperdiv/hyperdiv#49]
**Describe the bug**
The example vertical hd.divider code in the app doesn't work because the default height=100% leads to a height of 0 (one of those wonderful mysteries of css). 

**Reproduce**
The example code in the hyperdiv docs only works because of the flex styling of an ancestor element several levels higher than the example code. You can reproduce this bug in the hd.divider documents by setting the display to block for that ancestor element. Here's a screenshot, showing the bug and the ancestor element relative to the divider component. Note how there is no divider showing between item one and two:

![image](https://github.com/hyperdiv/hyperdiv/assets/707039/f74f600e-a90d-4a85-9e99-27485c844073)

**Test case**
Here's an app:

```
import hyperdiv as hd

router = hd.router()


@router.route("/")
def home():
    with hd.hbox():
        hd.text("default height=100% prevents the divider from showing ==>")
        hd.divider(vertical=True, spacing=1)
        hd.text("<=== right there")

    with hd.hbox():
        hd.text("setting height explicitly works ==>")
        hd.divider(vertical=True, spacing=1, height=1)
        hd.text("<== right there")


def main():
    router.run()


hd.run(main)

```

**Comment by mariusnita** [comment]
Thanks! I think if Hyperdiv sets the default height to `auto` instead of `100%` for `sl-divider[vertical]` it will fix this issue.
