### ISSUE TITLE
dialog.was_closed unexpectedly only works if it is set before dialog.opened set to True

### ISSUE THREAD

**Issue by tkriplean** [hyperdiv/hyperdiv#53]
The ordering of setting dialog to opened and defining a handler for dialog.was_closed unexpectedly matters. Perhaps it is unexpected because I'm coming from javascript where an element can be created and added to the DOM, and then have events hooked up afterwards.

I presume this applies to any Togglable component. And it might be more of a documentation issue. 

Demonstration:

```
import hyperdiv as hd

router = hd.router()


@router.route("/")
def home():
    with hd.dialog() as dialog:
        hd.text("yoyo")

    dialog.opened = True  # if you open the dialog before setting was closed

    if dialog.was_closed:
        # ...this will not print when you click the dialog close button
        print("WAS CLOSED!")

    # dialog.opened = True # ...but if you open the dialog after setting was_closed, it works


def main():
    router.run()


hd.run(main)
```

**Comment by mariusnita** [comment]
In this code:
```py
    dialog.opened = True

    if dialog.was_closed:
        print("WAS CLOSED!")
 ```

`was_closed` means "the close event fired and the dialog is currently in closed state". But this dialog can never be observed in closed state, since you always put it in opened state right before that check.

There appears to be a bug, probably in Shoelace, that lets you visibly close this dialog, even though it is instantly put back in opened state. I assume it's a timing bug where if the dialog is reopened while it is closing, it doesn't reopen properly.

If you share more about your use case I can think about this more.

**Comment by tkriplean** [comment]
Sure, I figured it out by looking at the code. It was just unexpected (and might therefore be a good candidate for a documentation example).

The use case is pretty basic. Here's an expanded example of the use case:

```
import hyperdiv as hd

router = hd.router()


@router.route("/")
def home():
    state = hd.state(dialog_is_open=False, dialog_canceled=False, dialog_affirmed=False)

    def close_dialog(take_action=False):
        state.dialog_is_open = False
        if take_action:
            state.dialog_affirmed = True
        else:
            state.dialog_canceled = True

    if state.dialog_is_open:
        # define the dialog
        with hd.dialog() as dialog:
            hd.text("yoyo")
            take_action = hd.button(
                "take action", variant="primary", slot=dialog.footer
            )
            cancel_button = hd.button("cancel", slot=dialog.footer)

        # open it up
        dialog.opened = True

        # set event handlers
        if take_action.clicked:
            close_dialog(take_action=True)
        if cancel_button.clicked or dialog.was_closed:
            close_dialog()

        hd.text("dialog is for sure open right now")

    else:
        open_dialog = hd.button("launch dialog")
        if open_dialog.clicked:
            state.dialog_is_open = True
            state.dialog_canceled = False
            state.dialog_affirmed = False

        if state.dialog_affirmed:
            hd.text("Take action!")
        if state.dialog_canceled:
            hd.text("Dialog canceled")


def main():
    router.run()


hd.run(main)
```

I think part of it is that "was_closed" is ambiguous. I think you mean that the dialog is in the state of being closed. But was_closed also sounds like an event, just like clicked. But if you named it 'closed' instead of 'was_closed' it would still have this ambiguity. Perhaps naming it 'is_closed' rather than 'was_closed' would help communicate that it is state and not an event.

Personally, I think that was_closed (or better, 'closed') *should* be an event prop that can be treated in the same way as clicked, because I think (admittedly, purely on intuition, so I could be wrong) that lines up with the most common use cases of dialogs. Namely, you create them, a user interacts with them, and when they're done with them, signaled by some closing event, we discard them. You don't like keep dialogs around or something to be opened and closed repeatedly. Treating dialogs as Togglable seems to me to not really capture the usual use case even though I understand you can conceive of them that way.

**Comment by mariusnita** [comment]
There seem to be a couple of concerns. First, dialogs are indeed persistent togglable objects that you can open and close repeatedly. That's how Hyperdiv/Shoelace works. 

Second, `was_closed` indeed works like an event. `visibility_changed` is an event and `was_closed` means `visibility_changed and not opened`. But yes maybe `was_closed` should be a pure event and not take `opened` into account at all.

Your code behaves strangely because you mutate `opened` in mainline code. In general this code will likely be behaving strangely:

```py
t = togglable_component()
t.opened = True
```

When the UI closes this component, the code re-runs, causing it to be immediately re-opened.

I suggest these changes to your code.

```diff
     if state.interacting_with_dialog:
         # define the dialog
-        with hd.dialog() as dialog:
+        with hd.dialog(opened=True) as dialog:
             hd.text("Lets get you started")
             take_action = hd.button(
                 "take action", variant="primary", slot=dialog.footer
             )
             cancel_button = hd.button("cancel", slot=dialog.footer)

-        # open it up
-        dialog.opened = True
-
         # set event handlers
         if take_action.clicked:
             dialog_done(take_action=True)
         if cancel_button.clicked or dialog.was_closed:
             dialog_done()
+            dialog.reset_prop("opened")

         hd.text("dialog is for sure open right now")
```

I also wonder what the top level motivation is for this code. Is it to avoid having a dialog in the dom when not in use? To me it seems like a lot of trouble to go through.

**Comment by mariusnita** [comment]
I'm closing this issue, with a note to self that perhaps `was_closed` should be a pure event, but made this related issue about the problem I noticed in Shoelace: https://github.com/hyperdiv/hyperdiv/issues/54

**Comment by tkriplean** [comment]
Thanks for the reset_prop reference, I didn't know about that. And setting opened=True in the constructor is better. 

> I also wonder what the top level motivation is for this code. Is it to avoid having a dialog in the dom when not in use? To me it seems like a lot of trouble to go through.

I have a fairly complex UI interaction I was previously facilitating in a dialog (specifying where in a video something else is anchored to). That "something else" is defined by the user in the main form. The complex UI interaction is not embedded in the form itself because it is entirely optional (and the system provides a default value that is probably correct ~80% of the time). The user can begin the optional dialog by clicking a button. The complex UI interaction includes an embedded YouTube video that does not need to be loaded unless the user actually decides to engage in the dialogue.

It sounds like the Hyperdiv way is to create all the dialogs you might want and turn them on and off as needed. I don't think that really fits the underlying metaphor of a "conversation with the user", but I can work with it. Still, it isn't the only reasonable approach, and it may be a stumbling block for those trying to learn Hyperdiv. 

Thanks for your hard work!

**Comment by mariusnita** [comment]
One related thought here is that the contents of a dialog don't have to be loaded in the dialog's body when the dialog is closed.

```py
with hd.dialog() as d:
  if d.opened:
    hd.text("Hello") # this isn't executed/loaded in the dom if the dialog is closed

if hd.button("Open").clicked:
  d.opened = True
```

You can also reuse a dialog:

As far as dialog being "conversational", I think HTML itself departed from that: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

With `<sl-dialog>` (which follows `<dialog>` I think), you put dialogs in the dom and then open/close them.
