### ISSUE TITLE
error in method `media_source`

### ISSUE THREAD

**Issue by fcoagz** [hyperdiv/hyperdiv#56]
I try to load an mp3 audio, looking at the example code of the module. But I have an error: 

```sh
  hd.media_source("./example.mp3")
TypeError: Component.__init__() takes 1 positional argument but 2 were given
```

code:

```py
import hyperdiv as hd

def main():
    with hd.audio() as audio:
        hd.media_source("./example.mp3")

        
hd.run(main)
```

If you could help me please<3

**Comment by mariusnita** [comment]
Thanks! The docs are misleading.

Try `hd.media_source(src="./example.mp3")`.

Btw you probably want `hd.media_source(src="/assets/example.mp3")` with the mp3 being placed in an assets directory.

See here: https://docs.hyperdiv.io/guide/static-assets

**Comment by fcoagz** [comment]
thank you bro<3 yes, I had not thought that it should be placed in a specific directory hahaha. by the way, incredible project bro, I'm using it to create a web ui for an ambitious project I'm creating

**Comment by fcoagz** [comment]
Example code in case anyone has had the same problem as me.

Create a directory called assets and place all your files that you want to display
```py
import hyperdiv as hd

def main():
    with hd.audio(controls = False) as audio:
        hd.media_source(src="assets/example.mp3")
    
    if audio.playing:
        if hd.button(
            "Pause",
            prefix_icon="pause",
            font_color="red"
        ).clicked:
            audio.pause()
    else:
        if hd.button(
            "Play",
            prefix_icon="play-fill",
            font_color="blue"
        ).clicked:
            audio.play()
        
hd.run(main)
```
