### ISSUE TITLE
errors in threaded task are never surfaced, logged or reported (ping example)

### ISSUE THREAD

**Issue by johnny-smitherson** [hyperdiv/hyperdiv#6]
In the ping example, if, for some reason, the `ping` task function throws, the error is not printed at the logs, not shown in the UI, and generally not observable in any way.

For example, intentionally changing the executable to a typo:

```
def ping(hostname):
    p = subprocess.Popen(["pingz", "-c", "1", hostname], stdout=subprocess.PIPE)
    out, err = p.communicate()
    return float(out.split(b"\n")[1].split(b" ")[-2].split(b"=")[1])
```

This causes the page to not display any numbers for the ping, but no error is displayed.

Instead, if we spam the logger ourselves:

```
def ping(hostname):
    import logging
    logging.warning('tick')
    p = subprocess.Popen(["pingz", "-c", "1", hostname], stdout=subprocess.PIPE)
    out, err = p.communicate()
    logging.warning('tock')
    return float(out.split(b"\n")[1].split(b" ")[-2].split(b"=")[1])
```

The first log works, but not the second one
```
[W 240222 01:31:47 ping_task:7] tick
[W 240222 01:31:48 ping_task:7] tick
[W 240222 01:31:49 ping_task:7] tick
[W 240222 01:31:50 ping_task:7] tick
```

Finally, if we capture the error ourselves, we get the correct logs:

```
def ping(hostname):
    import logging
    logging.warning('tick')
    try:
        p = subprocess.Popen(["pingz", "-c", "1", hostname], stdout=subprocess.PIPE)
        out, err = p.communicate()
    except Exception as e:
        logging.exception(e)
        raise
    logging.warning('tock')
    return float(out.split(b"\n")[1].split(b" ")[-2].split(b"=")[1])
```

```
[W 240222 01:33:31 ping_task:7] tick
[E 240222 01:33:31 ping_task:12] [Errno 2] No such file or directory: 'pingz'
    Traceback (most recent call last):
      File "/c/Users/john/Desktop/VIDOEGAME/ANOTHER_WORK_QUEUE/another-work-queue-ffs/scylla/ui_demos/ping/ping/ping_task.py", line 9, in ping
        p = subprocess.Popen(["pingz", "-c", "1", hostname], stdout=subprocess.PIPE)
      File "/opt/pypy/lib/pypy3.10/subprocess.py", line 986, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/opt/pypy/lib/pypy3.10/subprocess.py", line 1891, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'pingz'

```

used interpreter: Python 3.10.13 [PyPy 7.3.15 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux

suggestions:
- always log errors in task coroutines by checking future for errors and/or wrapping task around try/except
- nice to have: in debug setup, forward the error text to browser console
- nicer to have: option to show toast in browser corner with red text
  - this might lead to security problems if error message contains secrets, for example
- ignore all of the above, document the limitation, and show example where application handles its own errors

**Comment by mariusnita** [comment]
Thanks for reporting! Yes we should always log uncaught task errors, at the very least.

Btw I'm also interested in surfacing errors/stack traces in the UI like you suggest. That would make for a nice dev experience. This functionality can be automatically off when the app is in production mode.

**Comment by mariusnita** [comment]
Hi, Hyperdiv does currently surface stack traces in tasks, it's just that this particular `ping` app swallows the errors, here:
https://github.com/hyperdiv/hyperdiv-apps/blob/main/ping/ping/ping_task.py#L26-L27

The app is not fully robust to all the possible types of ping errors and if it fails for any reason, it just doesn't register the data point. A quick fix would be to explicitly log the stack trace in that exception handler.

**Comment by mariusnita** [comment]
I modified the ping app to log warnings when the ping command fails.

**Comment by mariusnita** [comment]
Thanks! That is a really cool trick.
