### ISSUE TITLE
[BUG] active pagination element not synced with carousel-item

### ISSUE THREAD

**Issue by chrishollandaise** [hyperdiv/hyperdiv#7]
## What's going on

I was testing out the carousel component from the docs page, and I noticed that active pagination element is always one step behind from carousel-item render. Very odd. 

I would expect when I click on either a pagination element or arrows, I expect them to be synced. 

## Demonstration
![carousel-demo](https://github.com/hyperdiv/hyperdiv/assets/26207348/5ec12fc0-c6e9-4c92-b2f1-9655c0223193)

**Comment by mariusnita** [comment]
Thanks! I'll try to repro and fix.

**Comment by mariusnita** [comment]
Btw what browser and OS are you using?

**Comment by johnny-smitherson** [comment]
i also saw some funny-looking bugs and performance problems - mine were caused by browser extensions (CanvasBlocker and a bunch of other fingerprint hardening stuff) - this package makes extensive use of canvas and advanced browser features, so try a fresh profile on your browser

**Comment by chrishollandaise** [comment]
> Btw what browser and OS are you using?

Darwin 22.6.0 arm64, it was tested on Firefox 122.0.1.

**Comment by chrishollandaise** [comment]
> i also saw some funny-looking bugs and performance problems - mine were caused by browser extensions (CanvasBlocker and a bunch of other fingerprint hardening stuff) - this package makes extensive use of canvas and advanced browser features, so try a fresh profile on your browser

Interesting. Unfortunately, I just tried on a guest profile on Chrome, still getting same exact issue.

**Comment by mariusnita** [comment]
@chrishollandaise do you observe a similar issue when you use sl-carousel on the Shoelace website? https://shoelace.style/components/carousel

I am unfortunately unable to repro on Firefox & Darwin 23.2.0, I'll keep trying to figure it out. I also notice that you don't see a sliding animation.

![carousel](https://github.com/hyperdiv/hyperdiv/assets/5980501/ef536319-b3a8-4023-86ab-1e10eea9bf7c)

**Comment by mariusnita** [comment]
> i also saw some funny-looking bugs and performance problems - mine were caused by browser extensions (CanvasBlocker and a bunch of other fingerprint hardening stuff) - this package makes extensive use of canvas and advanced browser features, so try a fresh profile on your browser

Hm, that's unfortunate. FWIW I don't think Hyperdiv uses canvas anywhere. Shoelace components are Web Components mostly wrapping vanilla HTML elements.

**Comment by chrishollandaise** [comment]
Yes, I do see similar behavior on the sl-carousel.

I discovered a couple of things. First, I noticed it has the correct behavior on Safari just without the animation.

Second, that's interesting you point out the animation. I have reduce motion on (`System Preferences > Accessibility > Display > Reduce motion`), and as soon as I turned it off, it works on my Chrome, Firefox, and Safari and has the animation!

Let me know if you can repro with reduce motion on. If so, then this is a bug on shoelace's end something to do when `prefers-reduced-motion` is true.

**Comment by mariusnita** [comment]
Good find! Yes I can repro the issue in Chrome and FF when I turn on reduce animation.

**Comment by chrishollandaise** [comment]
Sweet! I made a [issue on the shoelace repo](https://github.com/shoelace-style/shoelace/issues/1887). We'll see what happens then.

**Comment by mariusnita** [comment]
Tested that carousel works with reduce motion turned on 👍🏼
